apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiTokenSecretRef:
                  type: string
                senderEmail:
                  type: string
                mailgunConfig:      # New field for Mailgun configuration
                  type: object
                  properties:
                    apiKey:
                      type: string
                    domain:
                      type: string
  scope: Cluster
  names:
    plural: emailsenderconfigs
    singular: emailsenderconfig
    kind: EmailSenderConfig
    shortNames:
      - escfg
