apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                senderConfigRef:
                  type: string
                recipientEmail:
                  type: string
                subject:
                  type: string
                body:
                  type: string
                mailgunConfig:        # New field for Mailgun configuration
                  type: object
                  properties:
                    apiKey:
                      type: string
                    domain:
                      type: string
            status:
              type: object
              properties:
                deliveryStatus:
                  type: string
                messageId:
                  type: string
                error:
                  type: string
  scope: Cluster
  names:
    plural: emails
    singular: email
    kind: Email
    shortNames:
      - eml
