apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator-restricted-access
rules:
  # Grant read-only access to secrets in the email-operator-system namespace
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames:
      - namespaces/email-operator-system
  # Full access to Email and EmailSenderConfig resources
  - apiGroups:
      - email.batman.example.com
    resources:
      - emails
      - emails/finalizers
      - emails/status
      - emailsenderconfigs
      - emailsenderconfigs/finalizers
      - emailsenderconfigs/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
