apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator-read-api-token-secret  # Replace with a descriptive name if desired
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames:
      - namespaces/email-operator-system/mailgun-api-key  # Replace with the actual secret name
