apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: email-operator-secrets-rolebinding
subjects:
  - kind: ServiceAccount
    name: email-operator-email-operator-controller-manager
    namespace: email-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: email-operator-secrets-role
