apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-election-role
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-election-role-binding
subjects:
- kind: ServiceAccount
  name: email-operator-controller-manager
  namespace: email-operator-system
roleRef:
  kind: ClusterRole
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io
