apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: memcached-operator
    app.kubernetes.io/part-of: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-operator-system  # Ensure this matches the desired namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: email-operator-system  # Ensure this matches the namespace in service_account.yaml
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: email-operator
    app.kubernetes.io/part-of: email-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: email-operator-controller-manager  # Update this line
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: bruno74t/email-operator:v12.5
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        env:
          - name: MAILGUN_DOMAIN
            value: "sandbox949259d91ad141fa8fb2518c835ccf49.mailgun.org"
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun-api-token
                key: api-token
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
